[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Columns `1`, `product`, and `9` don't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Columns `1`, `product`, and `9` don't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't rename columns that don't exist.\n\033[31mx\033[39m Column `reg` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Columns `1`, `product`, and `9` don't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Columns `1`, `product`, and `9` don't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Join columns must be present in data.\n\033[31mx\033[39m Problem with `cd_uf`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: unexpected symbol in:\n\"      df1 #%>% dplyr::select(-product, -value) %>% dplyr::distinct(), \n      by\"\n"

Error: unexpected ')' in "    )"
 

Error in desc(value) : object 'value' not found
 

[1] "Error: Join columns must be present in data.\n\033[31mx\033[39m Problem with `cd_uf`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Join columns must be present in data.\n\033[31mx\033[39m Problem with `cd_uf`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Join columns must be present in data.\n\033[31mx\033[39m Problem with `country`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Join columns must be present in data.\n\033[31mx\033[39m Problem with `cd_uf`.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `country` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `country` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `product` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `var` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Must group by variables found in `.data`.\n* Column `cd_year` is not found.\n* Column `product` is not found.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

Error in is.data.frame(y) : object 'dic_uf' not found
 

Error in is.data.frame(y) : object 'dic_uf' not found
 

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `sg_uf` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Column `sg_uf` doesn't exist.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error: Can't subset columns that don't exist.\n\033[31mx\033[39m Locations 86, 87, 88, 89, 90, etc. don't exist.\n\033[34mℹ\033[39m There are only 85 columns.\n\033[90mRun `rlang::last_error()` to see where the error occurred.\033[39m\n"

[1] "Error in clean_names.default(.) : \n  No `clean_names()` method exists for the class list\nConsider janitor::make_clean_names() for other cases of manipulating vectors of names.\n"

Error in match.fun(FUN) : object 'f1' not found
 

